spring:
  application:
    name: todo-be
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: Asia/Seoul

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /docs
